path:
  model_directory: ./model-${exp.model_type}
  mlflow_dir: ./mlruns
exp:
  fs: 125
  N_fold: 5
  random_state: 100
  data_name: bcg
  model_type: convtr
  exp_detail: lr-${param_model.lr}_wd-${param_model.wd}_bs-${param_model.batch_size}_dropout-${param_model.dropout}_max_epochs-${param_trainer.max_epochs}_d_input-${param_model.d_input}_num_filters-${param_model.num_filters}_num_heads-${param_model.num_heads}_num_layer-${param_model.num_layer}_seed-${param_model.seed}
  exp_name: ${exp.data_name}-${exp.model_type}/${exp.exp_detail}
  subject_dict: ../../datasets/splitted/${exp.data_name}_dataset/signal_fold
  loader: waveform
  cv: cv
param_loader:
  ppg_norm: loc_z
  bp_norm: glob_mm
objective:
  type: val_mse
  mode: min
param_trainer:
  max_epochs: 100
  check_val_every_n_epoch: 2
  progress_bar_refresh_rate: 5
  gpus: '0'
  auto_lr_find: true
  auto_scale_batch_size: binsearch
param_early_stop:
  monitor: ${objective.type}
  min_delta: 0.0
  patience: 10
  verbose: true
  mode: ${objective.mode}
param_model:
  N_epoch: 256
  batch_size: 256
  feature_size: 1
  d_input: 64
  num_filters: 12
  num_heads: 2
  d_model: 96
  dropout: 0.1
  num_layer: 2
  d_output: 2
  batch_first: true
  lr: 0.001
  wd: 0
  seed: 0
  sample_step: 1
logger:
  param_ckpt:
    monitor: ${objective.type}
    filename: '{epoch:02d}-{${objective.type}:.3f}'
    save_top_k: 1
    mode: ${objective.mode}
